from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(941, 682)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 40, 281, 551))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ToolBarBox = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.ToolBarBox.setFont(font)
        self.ToolBarBox.setStyleSheet("background-color: rgb(219, 219, 219);")
        self.ToolBarBox.setObjectName("ToolBarBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.ToolBarBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 40, 241, 481))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.DecisionButton = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.DecisionButton.setObjectName("DecisionButton")
        self.gridLayout.addWidget(self.DecisionButton, 0, 2, 1, 1)
        self.FinalStateButton = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.FinalStateButton.setObjectName("FinalStateButton")
        self.gridLayout.addWidget(self.FinalStateButton, 1, 0, 1, 1)
        self.ActiveStateButton = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.ActiveStateButton.setObjectName("ActiveStateButton")
        self.gridLayout.addWidget(self.ActiveStateButton, 0, 0, 1, 1)
        self.ObjectInStateButton = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.ObjectInStateButton.setObjectName("ObjectInStateButton")
        self.gridLayout.addWidget(self.ObjectInStateButton, 1, 1, 1, 1)
        self.ComplexTransitionButton = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.ComplexTransitionButton.setObjectName("ComplexTransitionButton")
        self.gridLayout.addWidget(self.ComplexTransitionButton, 0, 1, 1, 1)
        self.SignalReceiptButton = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.SignalReceiptButton.setObjectName("SignalReceiptButton")
        self.gridLayout.addWidget(self.SignalReceiptButton, 1, 2, 1, 1)
        self.SignalSendingButton = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.SignalSendingButton.setObjectName("SignalSendingButton")
        self.gridLayout.addWidget(self.SignalSendingButton, 2, 0, 1, 1)
        self.StartStateButton = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.StartStateButton.setObjectName("StartStateButton")
        self.gridLayout.addWidget(self.StartStateButton, 2, 1, 1, 1)
        self.TransitinButton = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.TransitinButton.setObjectName("TransitinButton")
        self.gridLayout.addWidget(self.TransitinButton, 2, 2, 1, 1)
        self.horizontalLayout.addWidget(self.ToolBarBox)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(290, 40, 631, 551))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget_2)
        self.plainTextEdit.setStyleSheet("background-color: rgb(219, 219, 219);")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.horizontalLayout_2.addWidget(self.plainTextEdit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 941, 24))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ToolBarBox.setTitle(_translate("MainWindow", "Панель инструментов"))
        self.DecisionButton.setText(_translate("MainWindow", "Dscn"))
        self.FinalStateButton.setText(_translate("MainWindow", "Final"))
        self.ActiveStateButton.setText(_translate("MainWindow", "Active"))
        self.ObjectInStateButton.setText(_translate("MainWindow", "OIS"))
        self.ComplexTransitionButton.setText(_translate("MainWindow", "CmpTr"))
        self.SignalReceiptButton.setText(_translate("MainWindow", "SP"))
        self.SignalSendingButton.setText(_translate("MainWindow", "SSend"))
        self.StartStateButton.setText(_translate("MainWindow", "Start"))
        self.TransitinButton.setText(_translate("MainWindow", "Trans"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.menu_2.setTitle(_translate("MainWindow", "Статистика"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())